import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import ChatBot from "./components/ChatBot";
import { AppProvider } from "./Provider";

import "./globals.css";

// Initialize the Outfit font
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  // You can also specify weights if needed:
  // weight: ["300", "400", "500", "600", "700"],
  // If you want the variable font version (recommended):
  // variable: "--font-outfit",
  // style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "lefke-apartments",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.variable}>
      <body className="font-sans antialiased">
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}